@startuml Taller-Mecanico
!theme plain
top to bottom direction

package "src" {
  package "modelo" {
    package "vo" <<Folder>> {
      class ClienteVO
      class FacturaVO
      class MecanicoVO
      class PedidoVO
      class OrdenServicioVO
      class ProveedorVO
      class RecepcionistaVO
      class RepuestoVO
      class UserVO
      class VehiculoVO
    }

    package "UserDao" <<Folder>> {
      class ClienteDAO
      class FacturaDAO
      class MecanicoDAO
      class OrdenServicioDAO
      class PedidoDAO
      class ProveedorDAO
      class RecepcionistaDAO
      class RepuestoDAO
      class UserDAOJDBC
      class VehiculoDAO

    }

    package "conexion" <<Folder>> {
      class Conexion
    }
  }

  package "controlador" <<Frame>> {
    class ControladorActualizarEstado
    class ControladorAsignarOrden
    class ControladorConsultarEstado
    class ControladorDarDeBajaVehiculos
    class ControladorEstadoActual
    class ControladorFacturas
    class ControladorPedido
    class ControladorGestionProveedores
    class ControladorGestionRepuestos
    class ControladorHistorialServicios
    class ControladorLogin
    class ControladorOperacionesProveedores
    class ControladorOperacionesRepuestos
    class ControladorActualizarPedido
    class ControladorPrincipal
    class ControladorRegistrarOrdenServicio
    class ControladorRegistrarVehiculo
    class ControladorRegistro
    class ControladorRegistroCliente
    class Main
  }

  package "vista" <<Frame>> {
    class VentanaActualizarEstado
    class AdministradorPanel
    class AnadirProveedor
    class AnadirRepuesto
    class AsignarOrden
    class ClientePanel
    class VentanaConsultarEstado
    class DarDeBajaVehiculos
    class EliminarProveedor
    class EliminarRepuesto
    class EstadoActual
    class Facturas
    class GestionPedidos
    class GestionProveedores
    class GestionRepuestos
    class HistorialCliente
    class LoginWindow
    class PanelMecanico
    class ModificarProveedor
    class ModificarRepuesto
    class RegistrarOrdenServicio
    class ActualizarEstadoPedido
    class PrincipalWindow
    class RecepcionistaPanel
    class RegistroWindow
    class RegistrarCliente
    class RegistrarVehiculo
    class VentanaCliente
    class VentanaMecanico
    class VentanaRecepcionista
  }
}

' Relaciones
vista --> controlador
controlador --> modelo.UserDao
modelo.UserDao --> modelo.vo
modelo.UserDao --> modelo.conexion

note right of modelo.vo
  <b>Value Objects</b>
  • ClienteVO
  • FacturaVO
  • MecanicoVO
  • PedidoVO
  • VehiculoVO
  • Etc  
end note

note left of modelo.UserDao
  <b>Patrón DAO</b>
  • Usan Conexion 
  • Ej: ClienteDAO
end note
@enduml