@startuml packages_MiProyecto_controlador
set namespaceSeparator none
package "src.controlador" as src.controlador {
}
package "src.controlador.ControladorActualizarEstado" as src.controlador.ControladorActualizarEstado {
}
package "src.controlador.ControladorAsignarOrden" as src.controlador.ControladorAsignarOrden {
}
package "src.controlador.ControladorConsultarEstado" as src.controlador.ControladorConsultarEstado {
}
package "src.controlador.ControladorDarDeBajaVehiculos" as src.controlador.ControladorDarDeBajaVehiculos {
}
package "src.controlador.ControladorEstadoActual" as src.controlador.ControladorEstadoActual {
}
package "src.controlador.ControladorFactura" as src.controlador.ControladorFactura {
}
package "src.controlador.ControladorGestionPedidos" as src.controlador.ControladorGestionPedidos {
}
package "src.controlador.ControladorGestionProveedores" as src.controlador.ControladorGestionProveedores {
}
package "src.controlador.ControladorGestionRepuestos" as src.controlador.ControladorGestionRepuestos {
}
package "src.controlador.ControladorHistorialServicios" as src.controlador.ControladorHistorialServicios {
}
package "src.controlador.ControladorLogin" as src.controlador.ControladorLogin {
}
package "src.controlador.ControladorOperacionesProveedores" as src.controlador.ControladorOperacionesProveedores {
}
package "src.controlador.ControladorOperacionesRepuestos" as src.controlador.ControladorOperacionesRepuestos {
}
package "src.controlador.ControladorPedidosRecibidos" as src.controlador.ControladorPedidosRecibidos {
}
package "src.controlador.ControladorPrincipal" as src.controlador.ControladorPrincipal {
}
package "src.controlador.ControladorRegistrarOrdenServicio" as src.controlador.ControladorRegistrarOrdenServicio {
}
package "src.controlador.ControladorRegistrarVehiculo" as src.controlador.ControladorRegistrarVehiculo {
}
package "src.controlador.ControladorRegistro" as src.controlador.ControladorRegistro {
}
package "src.controlador.ControladorRegistroCliente" as src.controlador.ControladorRegistroCliente {
}
package "src.controlador.main" as src.controlador.main {
}
src.controlador.main --> src.controlador.ControladorPrincipal
@enduml
